name: Tests

on: push

jobs:
  test-examples:
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - wasm32-wasi

        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            runner: test
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            runner: test 
          - target: x86_64-apple-darwin
            os: macos-latest
            runner: test  
          - target: wasm32-wasi
            os: ubuntu-latest
            runner: wasi test

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Restore cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
            ~/.wasmtime
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
        key: cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-${{ matrix.target }}-

    - run: rustup override set nightly
    - run: rustup target add ${{ matrix.target }}
    
    - if: matrix.target == 'wasm32-wasi'
      name: Install Wasmtime
      run: cargo install wasmtime-cli

    - if: matrix.target == 'wasm32-wasi'
      name: Install WASI runner
      run: cargo install cargo-wasi

    - run: source ~/.bashrc && cargo +nightly ${{ matrix.runner }} --all-features
